# Generated by Django 5.0.4 on 2024-05-07 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SHNKSystemsModel',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_shnk.abstractbasemodel')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('systems_name_uz', models.CharField(max_length=255, unique=True)),
                ('systems_name_ru', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'SHNK Systems',
                'db_table': 'shnk_systems',
            },
            bases=('app_shnk.abstractbasemodel',),
        ),
    ]
