# Generated by Django 5.0.4 on 2024-05-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHNKGroupsModel',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_shnk.abstractbasemodel')),
                ('group_code', models.CharField(max_length=15, unique=True)),
                ('group_name_uz', models.CharField(max_length=255)),
                ('group_name_ru', models.CharField(max_length=255)),
                ('group_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shnk.shnksystemsmodel')),
            ],
            options={
                'verbose_name_plural': 'SHNK Groups',
                'db_table': 'shnk_groups',
            },
            bases=('app_shnk.abstractbasemodel',),
        ),
    ]
