# Generated by Django 5.0.4 on 2024-05-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0002_shnkgroupsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHNKTypesModel',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_shnk.abstractbasemodel')),
                ('type_name_uz', models.CharField(max_length=255, unique=True)),
                ('type_name_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('type_description_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('type_description_ru', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'SHNK Types',
                'db_table': 'shnk_types',
            },
            bases=('app_shnk.abstractbasemodel',),
        ),
    ]
