# Generated by Django 5.0.4 on 2024-05-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0003_shnktypesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHNKDocumentsModel',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_shnk.abstractbasemodel')),
                ('shnk_name_uz', models.CharField(max_length=255, unique=True)),
                ('shnk_name_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('shnk_code', models.CharField(max_length=10, unique=True)),
                ('shnk_file_uz', models.FileField(blank=True, null=True, upload_to='shnk')),
                ('shnk_file_ru', models.FileField(blank=True, null=True, upload_to='shnk')),
                ('shnk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shnk.shnkgroupsmodel')),
                ('shnk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shnk.shnktypesmodel')),
            ],
            options={
                'verbose_name_plural': 'SHNK Documents',
                'db_table': 'shnk_documents',
            },
            bases=('app_shnk.abstractbasemodel',),
        ),
    ]
