# Generated by Django 5.0.4 on 2024-05-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shnk', '0004_shnkdocumentsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHNKPartsModel',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_shnk.abstractbasemodel')),
                ('part_title_uz', models.CharField(max_length=255)),
                ('part_title_ru', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=10)),
                ('part_text_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('part_text_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('part_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shnk.shnkdocumentsmodel')),
            ],
            options={
                'verbose_name_plural': 'SHNK Parts',
                'db_table': 'shnk_parts',
            },
            bases=('app_shnk.abstractbasemodel',),
        ),
    ]
